<?php
namespace Aura\Marshal;

use Yoast\PHPUnitPolyfills\TestCases\TestCase;

/**
 * Test class for Data.
 * Generated by PHPUnit on 2011-11-26 at 14:22:58.
 */
class DataTest extends TestCase
{
    /**
     * @var Data
     */
    protected $data;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function set_up(): void
    {
        parent::set_up();
        $this->data = new Data([
            'foo' => 'bar',
            'baz' => 'dib',
            'zim' => 'gir',
        ]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tear_down(): void
    {
        parent::tear_down();
    }

    public function testOffsetExistsAndUnset(): void
    {
        $this->assertTrue($this->data->offsetExists('foo'));
        $this->data->offsetUnset('foo');
        $this->assertFalse($this->data->offsetExists('foo'));
    }

    public function testOffsetSetAndGet(): void
    {
        $this->data->offsetSet('irk', 'doom');
        $this->assertSame('doom', $this->data->offsetGet('irk'));
    }

    public function testCount(): void
    {
        $this->assertSame(3, $this->data->count());
    }

    public function testGetIterator(): void
    {
        $this->assertInstanceOf('Aura\Marshal\DataIterator', $this->data->getIterator());
    }
}
