<?php
namespace Aura\Marshal;

use Aura\Marshal\Entity\GenericEntity;
use Aura\Marshal\MockEntity;
use Aura\Marshal\Entity\Builder;
use Aura\Marshal\MockEntityBuilder;
use Aura\Marshal\Lazy\Builder as LazyBuilder;
use Aura\Marshal\Lazy\GenericLazy;
use Yoast\PHPUnitPolyfills\TestCases\TestCase;

/**
 * Test class for Entity.
 * Generated by PHPUnit on 2011-11-26 at 14:30:57.
 */
class EntityTest extends TestCase
{
    /**
     * @return array<string, string|GenericLazy>
     */
    protected function getData()
    {
        return [
            'foo' => 'bar',
            'baz' => 'dim',
            'zim' => 'gir',
            'related' => new GenericLazy(new MockRelation),
        ];
    }

    /**
     * @return GenericEntity
     */
    protected function newGenericEntity()
    {
        $builder = new Builder;
        return $builder->newInstance($this->getData());
    }

    /**
     * @return MockEntity
     */
    protected function newMockEntity()
    {
        $builder = new MockEntityBuilder;
        return $builder->newInstance($this->getData());
    }

    public function testMagicArrayAccess(): void
    {
        $entity = $this->newGenericEntity();

        // check set/get
        $entity->irk = 'doom';
        $this->assertSame('doom', $entity->irk);

        // check isset/unset
        $this->assertTrue(isset($entity->foo));
        unset($entity->foo);
        $this->assertFalse(isset($entity->foo));

        $this->assertFalse(isset($entity->newfield));

        $entity->newfield = 'something';
        $this->assertTrue(isset($entity->newfield));

        unset($entity->newfield);
        $this->assertFalse(isset($entity->newfield));

        // check relateds
        $actual = $entity->related;
        $expect = (object) ['foreign_field' => 'foreign_value'];
        $this->assertEquals($expect, $actual);
    }

    public function testMagicPropertyAccess(): void
    {
        $entity = $this->newMockEntity();

        // check set/get
        $entity->irk = 'doom';
        $this->assertSame('doom', $entity->irk);

        // check isset/unset
        $this->assertTrue(isset($entity->foo));
        unset($entity->foo);
        $this->assertFalse(isset($entity->foo));

        $this->assertFalse(isset($entity->newfield));

        $entity->newfield = 'something';
        $this->assertTrue(isset($entity->newfield));

        unset($entity->newfield);
        $this->assertFalse(isset($entity->newfield));

        // check relateds
        $actual = $entity->related;
        $expect = (object) ['foreign_field' => 'foreign_value'];
        $this->assertEquals($expect, $actual);
    }

    public function testToArray(): void
    {
        $entity = $this->newGenericEntity();
        $expected = [
            'foo' => 'bar',
            'baz' => 'dim',
            'zim' => 'gir',
            'related' => [
                'foreign_field' => 'foreign_value',
            ],
        ];
        $actual = $entity->toArray();
        $this->assertEquals($expected, $actual);
    }
}
