<?php
namespace Aura\Marshal;

use Aura\Marshal\MockEntity;
use Aura\Marshal\Entity\Builder;
use Aura\Marshal\MockEntityBuilder;
use Aura\Marshal\Lazy\Builder as LazyBuilder;
use Aura\Marshal\Lazy\GenericLazy;

/**
 * Test class for Entity.
 * Generated by PHPUnit on 2011-11-26 at 14:30:57.
 */
class EntityTest extends \PHPUnit_Framework_TestCase
{
    protected function getData()
    {
        return [
            'foo' => 'bar',
            'baz' => 'dim',
            'zim' => 'gir',
            'related' => new GenericLazy(new MockRelation),
        ];
    }

    protected function newStdClass()
    {
        $builder = new Builder;
        return $builder->newInstance($this->getData());
    }

    protected function newMockEntity()
    {
        $builder = new MockEntityBuilder;
        return $builder->newInstance($this->getData());
    }

    public function testMagicArrayAccess()
    {
        $entity = $this->newStdClass();

        // custom $isset is required since MockEntity has only protected properties
        $isset = \Closure::bind(function ($object, $prop) {
            return isset($object->$prop);
        }, null, get_class($entity));

        // check set/get
        $entity->irk = 'doom';
        $this->assertSame('doom', $entity->irk);

        // check isset/unset
        $this->assertTrue($isset($entity, 'foo'));
        unset($entity->foo);
        $this->assertFalse($isset($entity, 'foo'));

        $this->assertFalse($isset($entity, 'newfield'));

        $entity->newfield = 'something';
        $this->assertTrue($isset($entity, 'newfield'));

        unset($entity->newfield);
        $this->assertFalse($isset($entity, 'newfield'));

        // check relateds
        $actual = $entity->related;
        $expect = (object) ['foreign_field' => 'foreign_value'];
        $this->assertEquals($expect, $actual);
    }

    public function testMagicPropertyAccess()
    {
        $entity = $this->newMockEntity();

        // custom $isset is required since MockEntity has only protected properties
        $isset = \Closure::bind(function ($object, $prop) {
            return isset($object->$prop);
        }, null, get_class($entity));

        // custom $unset is required since MockEntity has only protected properties
        $unset = \Closure::bind(function ($object, $prop) {
            unset($object->$prop);
        }, null, get_class($entity));

        // check set/get
        $entity->irk = 'doom';
        $this->assertSame('doom', $entity->irk);

        // check isset/unset
        $this->assertTrue($isset($entity, 'foo'));
        $unset($entity, 'foo');
        $this->assertFalse($isset($entity, 'foo'));

        $this->assertFalse($isset($entity, 'newfield'));

        $entity->newfield = 'something';
        $this->assertTrue($isset($entity, 'newfield'));

        unset($entity->newfield);
        $this->assertFalse($isset($entity, 'newfield'));

        // check relateds
        $actual = $entity->related;
        $expect = (object) ['foreign_field' => 'foreign_value'];
        $this->assertEquals($expect, $actual);
    }
}
