<?php
namespace Aura\Marshal;
use Aura\Marshal\Record\GenericRecord;
use Aura\Marshal\MockType;

/**
 * Test class for Record.
 * Generated by PHPUnit on 2011-11-26 at 14:30:57.
 */
class RecordTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GenericRecord
     */
    protected $record;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $data = [
            'foo' => 'bar',
            'baz' => 'dim',
            'zim' => 'gir',
            'numeric' => '123',
            'zero' => 0,
            'falsy' => false,
            'nully' => null,
            'related' => 'related_record',
        ];
        
        $type = new MockType;
        
        // add a fake relation so we can check changes on relationships
        $type->addFakeRelation('related');
        
        $this->record = new GenericRecord($data, $type);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
    
    public function testSetAndGet()
    {
        $this->record->irk = 'doom';
        $this->assertSame('doom', $this->record->irk);
    }
    
    public function testIssetAndUnset()
    {
        $this->assertTrue(isset($this->record->foo));
        unset($this->record->foo);
        $this->assertFalse(isset($this->record->foo));
        
        $this->assertFalse(isset($this->record->newfield));
        
        $this->record->newfield = 'something';
        $this->assertTrue(isset($this->record->newfield));
        
        unset($this->record->newfield);
        $this->assertFalse(isset($this->record->newfield));
    }
}
